fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/pgomersbach/test-profile_base.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    profile_puppetmaster: "https://github.com/pgomersbach/test-profile_puppetmaster.git"
  symlinks:
    role_deployserver: "#{source_dir}"
