fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/pgomersbach/test-profile_base.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    puppetdb: "https://github.com/puppetlabs/puppetlabs-puppetdb.git"
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    firewall: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    file_concat: "git://github.com/electrical/puppet-lib-file_concat.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt"
    profile_puppetmaster: "https://github.com/pgomersbach/test-profile_puppetmaster.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"

  symlinks:
    role_deployserver: "#{source_dir}"
