AMI:
  ubuntu1204:
    :image:
      :foss: ami-01470531
    :region: us-west-2

  ubuntu1404:
    :image:
      :foss: ami-6989a659
    :region: us-west-2

  centos65:
    :image:
      :foss: ami-56e48766
    :region: us-west-2

